#!/bin/bash

# Prompt the user for their username
read -p "Enter your username: " username

# Define the URL of the file to download
url="https://github.com/ventoy/PXE/releases/download/v1.0.19/iventoy-1.0.19-linux-free.tar.gz"

# Define the path to the user's home directory
user_home="/home/$username"

# Download the file
wget "$url" -O "$user_home/iventoy-1.0.19-linux-free.tar.gz"

# Extract the file to the user's home directory
tar -xzf "$user_home/iventoy-1.0.19-linux-free.tar.gz" -C "$user_home"

# Delete the downloaded tar.gz file
rm "$user_home/iventoy-1.0.19-linux-free.tar.gz"

# Construct the path to iventoy.sh
IVENTOY_PATH="$user_home/iventoy-1.0.19/iventoy.sh"

# Define the cron job using the constructed path
CRON_JOB="@reboot sleep  15 && /bin/bash -c 'sudo $IVENTOY_PATH -R start'"

# Check if the cron job already exists
if ! sudo crontab -l | grep -q "$CRON_JOB"; then
    # Add the cron job
    (sudo crontab -l; echo "$CRON_JOB") | sudo crontab -
    echo "Cron job added successfully."
else
    echo "Cron job already exists."
fi

echo "Download, extraction, and crontab configuration completed. Files are in $user_home."
